/*
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGraphQLScopeProvider extends DelegatingScopeProvider {
}
