/**
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.graphQL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Argument</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.katmatt.graphql.graphQL.Argument#getArgumentDefinition <em>Argument Definition</em>}</li>
 *   <li>{@link io.github.katmatt.graphql.graphQL.Argument#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getArgument()
 * @model
 * @generated
 */
public interface Argument extends EObject
{
  /**
   * Returns the value of the '<em><b>Argument Definition</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument Definition</em>' reference.
   * @see #setArgumentDefinition(InputValueDefinition)
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getArgument_ArgumentDefinition()
   * @model
   * @generated
   */
  InputValueDefinition getArgumentDefinition();

  /**
   * Sets the value of the '{@link io.github.katmatt.graphql.graphQL.Argument#getArgumentDefinition <em>Argument Definition</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Argument Definition</em>' reference.
   * @see #getArgumentDefinition()
   * @generated
   */
  void setArgumentDefinition(InputValueDefinition value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(ConstValue)
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getArgument_Value()
   * @model containment="true"
   * @generated
   */
  ConstValue getValue();

  /**
   * Sets the value of the '{@link io.github.katmatt.graphql.graphQL.Argument#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(ConstValue value);

} // Argument
