/**
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.graphQL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Directive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.katmatt.graphql.graphQL.Directive#getDirective <em>Directive</em>}</li>
 *   <li>{@link io.github.katmatt.graphql.graphQL.Directive#getArguments <em>Arguments</em>}</li>
 * </ul>
 *
 * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getDirective()
 * @model
 * @generated
 */
public interface Directive extends EObject
{
  /**
   * Returns the value of the '<em><b>Directive</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Directive</em>' reference.
   * @see #setDirective(DirectiveDefinition)
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getDirective_Directive()
   * @model
   * @generated
   */
  DirectiveDefinition getDirective();

  /**
   * Sets the value of the '{@link io.github.katmatt.graphql.graphQL.Directive#getDirective <em>Directive</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Directive</em>' reference.
   * @see #getDirective()
   * @generated
   */
  void setDirective(DirectiveDefinition value);

  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference list.
   * The list contents are of type {@link io.github.katmatt.graphql.graphQL.Argument}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference list.
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getDirective_Arguments()
   * @model containment="true"
   * @generated
   */
  EList<Argument> getArguments();

} // Directive
