/**
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.graphQL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Directive Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.katmatt.graphql.graphQL.DirectiveDefinition#getDescription <em>Description</em>}</li>
 *   <li>{@link io.github.katmatt.graphql.graphQL.DirectiveDefinition#getName <em>Name</em>}</li>
 *   <li>{@link io.github.katmatt.graphql.graphQL.DirectiveDefinition#getArgumentDefinitions <em>Argument Definitions</em>}</li>
 *   <li>{@link io.github.katmatt.graphql.graphQL.DirectiveDefinition#isRepeatable <em>Repeatable</em>}</li>
 *   <li>{@link io.github.katmatt.graphql.graphQL.DirectiveDefinition#getDirectiveLocations <em>Directive Locations</em>}</li>
 * </ul>
 *
 * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getDirectiveDefinition()
 * @model
 * @generated
 */
public interface DirectiveDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' containment reference.
   * @see #setDescription(StringValue)
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getDirectiveDefinition_Description()
   * @model containment="true"
   * @generated
   */
  StringValue getDescription();

  /**
   * Sets the value of the '{@link io.github.katmatt.graphql.graphQL.DirectiveDefinition#getDescription <em>Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' containment reference.
   * @see #getDescription()
   * @generated
   */
  void setDescription(StringValue value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getDirectiveDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.github.katmatt.graphql.graphQL.DirectiveDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Argument Definitions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument Definitions</em>' containment reference.
   * @see #setArgumentDefinitions(ArgumentsDefinition)
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getDirectiveDefinition_ArgumentDefinitions()
   * @model containment="true"
   * @generated
   */
  ArgumentsDefinition getArgumentDefinitions();

  /**
   * Sets the value of the '{@link io.github.katmatt.graphql.graphQL.DirectiveDefinition#getArgumentDefinitions <em>Argument Definitions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Argument Definitions</em>' containment reference.
   * @see #getArgumentDefinitions()
   * @generated
   */
  void setArgumentDefinitions(ArgumentsDefinition value);

  /**
   * Returns the value of the '<em><b>Repeatable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repeatable</em>' attribute.
   * @see #setRepeatable(boolean)
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getDirectiveDefinition_Repeatable()
   * @model
   * @generated
   */
  boolean isRepeatable();

  /**
   * Sets the value of the '{@link io.github.katmatt.graphql.graphQL.DirectiveDefinition#isRepeatable <em>Repeatable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Repeatable</em>' attribute.
   * @see #isRepeatable()
   * @generated
   */
  void setRepeatable(boolean value);

  /**
   * Returns the value of the '<em><b>Directive Locations</b></em>' containment reference list.
   * The list contents are of type {@link io.github.katmatt.graphql.graphQL.DirectiveLocations}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Directive Locations</em>' containment reference list.
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getDirectiveDefinition_DirectiveLocations()
   * @model containment="true"
   * @generated
   */
  EList<DirectiveLocations> getDirectiveLocations();

} // DirectiveDefinition
