/**
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.graphQL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Type Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.katmatt.graphql.graphQL.EnumTypeDefinition#getValueDefinitions <em>Value Definitions</em>}</li>
 * </ul>
 *
 * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getEnumTypeDefinition()
 * @model
 * @generated
 */
public interface EnumTypeDefinition extends TypeDefinition
{
  /**
   * Returns the value of the '<em><b>Value Definitions</b></em>' containment reference list.
   * The list contents are of type {@link io.github.katmatt.graphql.graphQL.EnumValueDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Definitions</em>' containment reference list.
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getEnumTypeDefinition_ValueDefinitions()
   * @model containment="true"
   * @generated
   */
  EList<EnumValueDefinition> getValueDefinitions();

} // EnumTypeDefinition
