/**
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.graphQL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see io.github.katmatt.graphql.graphQL.GraphQLPackage
 * @generated
 */
public interface GraphQLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GraphQLFactory eINSTANCE = io.github.katmatt.graphql.graphQL.impl.GraphQLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Type System Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type System Definition</em>'.
   * @generated
   */
  TypeSystemDefinition createTypeSystemDefinition();

  /**
   * Returns a new object of class '<em>Schema Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Schema Definition</em>'.
   * @generated
   */
  SchemaDefinition createSchemaDefinition();

  /**
   * Returns a new object of class '<em>Root Operation Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Root Operation Type Definition</em>'.
   * @generated
   */
  RootOperationTypeDefinition createRootOperationTypeDefinition();

  /**
   * Returns a new object of class '<em>Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Definition</em>'.
   * @generated
   */
  TypeDefinition createTypeDefinition();

  /**
   * Returns a new object of class '<em>Scalar Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scalar Type Definition</em>'.
   * @generated
   */
  ScalarTypeDefinition createScalarTypeDefinition();

  /**
   * Returns a new object of class '<em>Object Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Object Type Definition</em>'.
   * @generated
   */
  ObjectTypeDefinition createObjectTypeDefinition();

  /**
   * Returns a new object of class '<em>Interface Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interface Definition</em>'.
   * @generated
   */
  InterfaceDefinition createInterfaceDefinition();

  /**
   * Returns a new object of class '<em>Field Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Field Definition</em>'.
   * @generated
   */
  FieldDefinition createFieldDefinition();

  /**
   * Returns a new object of class '<em>Union Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Union Type Definition</em>'.
   * @generated
   */
  UnionTypeDefinition createUnionTypeDefinition();

  /**
   * Returns a new object of class '<em>Enum Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enum Type Definition</em>'.
   * @generated
   */
  EnumTypeDefinition createEnumTypeDefinition();

  /**
   * Returns a new object of class '<em>Enum Value Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enum Value Definition</em>'.
   * @generated
   */
  EnumValueDefinition createEnumValueDefinition();

  /**
   * Returns a new object of class '<em>Input Object Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Input Object Type Definition</em>'.
   * @generated
   */
  InputObjectTypeDefinition createInputObjectTypeDefinition();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GraphQLPackage getGraphQLPackage();

} //GraphQLFactory
