/**
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.graphQL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see io.github.katmatt.graphql.graphQL.GraphQLPackage
 * @generated
 */
public interface GraphQLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GraphQLFactory eINSTANCE = io.github.katmatt.graphql.graphQL.impl.GraphQLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Type System Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type System Definition</em>'.
   * @generated
   */
  TypeSystemDefinition createTypeSystemDefinition();

  /**
   * Returns a new object of class '<em>Schema Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Schema Definition</em>'.
   * @generated
   */
  SchemaDefinition createSchemaDefinition();

  /**
   * Returns a new object of class '<em>Root Operation Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Root Operation Type Definition</em>'.
   * @generated
   */
  RootOperationTypeDefinition createRootOperationTypeDefinition();

  /**
   * Returns a new object of class '<em>Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Definition</em>'.
   * @generated
   */
  TypeDefinition createTypeDefinition();

  /**
   * Returns a new object of class '<em>Scalar Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scalar Type Definition</em>'.
   * @generated
   */
  ScalarTypeDefinition createScalarTypeDefinition();

  /**
   * Returns a new object of class '<em>Object Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Object Type Definition</em>'.
   * @generated
   */
  ObjectTypeDefinition createObjectTypeDefinition();

  /**
   * Returns a new object of class '<em>Interface Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interface Definition</em>'.
   * @generated
   */
  InterfaceDefinition createInterfaceDefinition();

  /**
   * Returns a new object of class '<em>Field Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Field Definition</em>'.
   * @generated
   */
  FieldDefinition createFieldDefinition();

  /**
   * Returns a new object of class '<em>Union Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Union Type Definition</em>'.
   * @generated
   */
  UnionTypeDefinition createUnionTypeDefinition();

  /**
   * Returns a new object of class '<em>Enum Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enum Type Definition</em>'.
   * @generated
   */
  EnumTypeDefinition createEnumTypeDefinition();

  /**
   * Returns a new object of class '<em>Enum Value Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enum Value Definition</em>'.
   * @generated
   */
  EnumValueDefinition createEnumValueDefinition();

  /**
   * Returns a new object of class '<em>Input Object Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Input Object Type Definition</em>'.
   * @generated
   */
  InputObjectTypeDefinition createInputObjectTypeDefinition();

  /**
   * Returns a new object of class '<em>Input Value Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Input Value Definition</em>'.
   * @generated
   */
  InputValueDefinition createInputValueDefinition();

  /**
   * Returns a new object of class '<em>Intersection Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Intersection Type</em>'.
   * @generated
   */
  IntersectionType createIntersectionType();

  /**
   * Returns a new object of class '<em>Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type</em>'.
   * @generated
   */
  Type createType();

  /**
   * Returns a new object of class '<em>Named Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Named Type</em>'.
   * @generated
   */
  NamedType createNamedType();

  /**
   * Returns a new object of class '<em>List Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>List Type</em>'.
   * @generated
   */
  ListType createListType();

  /**
   * Returns a new object of class '<em>Int Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Value</em>'.
   * @generated
   */
  IntValue createIntValue();

  /**
   * Returns a new object of class '<em>Float Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Float Value</em>'.
   * @generated
   */
  FloatValue createFloatValue();

  /**
   * Returns a new object of class '<em>Null Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Null Value</em>'.
   * @generated
   */
  NullValue createNullValue();

  /**
   * Returns a new object of class '<em>String Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Value</em>'.
   * @generated
   */
  StringValue createStringValue();

  /**
   * Returns a new object of class '<em>Boolean Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boolean Value</em>'.
   * @generated
   */
  BooleanValue createBooleanValue();

  /**
   * Returns a new object of class '<em>Enum Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enum Value</em>'.
   * @generated
   */
  EnumValue createEnumValue();

  /**
   * Returns a new object of class '<em>Object Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Object Value</em>'.
   * @generated
   */
  ObjectValue createObjectValue();

  /**
   * Returns a new object of class '<em>Object Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Object Field</em>'.
   * @generated
   */
  ObjectField createObjectField();

  /**
   * Returns a new object of class '<em>Const Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Const Value</em>'.
   * @generated
   */
  ConstValue createConstValue();

  /**
   * Returns a new object of class '<em>List Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>List Value</em>'.
   * @generated
   */
  ListValue createListValue();

  /**
   * Returns a new object of class '<em>Directive Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Directive Definition</em>'.
   * @generated
   */
  DirectiveDefinition createDirectiveDefinition();

  /**
   * Returns a new object of class '<em>Arguments Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arguments Definition</em>'.
   * @generated
   */
  ArgumentsDefinition createArgumentsDefinition();

  /**
   * Returns a new object of class '<em>Directive Locations</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Directive Locations</em>'.
   * @generated
   */
  DirectiveLocations createDirectiveLocations();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GraphQLPackage getGraphQLPackage();

} //GraphQLFactory
