/**
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.graphQL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see io.github.katmatt.graphql.graphQL.GraphQLFactory
 * @model kind="package"
 * @generated
 */
public interface GraphQLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "graphQL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.github.io/katmatt/graphql/GraphQL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "graphQL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GraphQLPackage eINSTANCE = io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl.init();

  /**
   * The meta object id for the '{@link io.github.katmatt.graphql.graphQL.impl.TypeSystemDefinitionImpl <em>Type System Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.katmatt.graphql.graphQL.impl.TypeSystemDefinitionImpl
   * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getTypeSystemDefinition()
   * @generated
   */
  int TYPE_SYSTEM_DEFINITION = 0;

  /**
   * The feature id for the '<em><b>Schema Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_SYSTEM_DEFINITION__SCHEMA_DEFINITIONS = 0;

  /**
   * The feature id for the '<em><b>Type Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_SYSTEM_DEFINITION__TYPE_DEFINITIONS = 1;

  /**
   * The number of structural features of the '<em>Type System Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_SYSTEM_DEFINITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.github.katmatt.graphql.graphQL.impl.SchemaDefinitionImpl <em>Schema Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.katmatt.graphql.graphQL.impl.SchemaDefinitionImpl
   * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getSchemaDefinition()
   * @generated
   */
  int SCHEMA_DEFINITION = 1;

  /**
   * The feature id for the '<em><b>Type Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA_DEFINITION__TYPE_DEFINITIONS = 0;

  /**
   * The number of structural features of the '<em>Schema Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA_DEFINITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.github.katmatt.graphql.graphQL.impl.RootOperationTypeDefinitionImpl <em>Root Operation Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.katmatt.graphql.graphQL.impl.RootOperationTypeDefinitionImpl
   * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getRootOperationTypeDefinition()
   * @generated
   */
  int ROOT_OPERATION_TYPE_DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Operation Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT_OPERATION_TYPE_DEFINITION__OPERATION_TYPE = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT_OPERATION_TYPE_DEFINITION__TYPE = 1;

  /**
   * The number of structural features of the '<em>Root Operation Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT_OPERATION_TYPE_DEFINITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.github.katmatt.graphql.graphQL.impl.TypeDefinitionImpl <em>Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.katmatt.graphql.graphQL.impl.TypeDefinitionImpl
   * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getTypeDefinition()
   * @generated
   */
  int TYPE_DEFINITION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_DEFINITION__NAME = 0;

  /**
   * The number of structural features of the '<em>Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_DEFINITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.github.katmatt.graphql.graphQL.impl.ScalarTypeDefinitionImpl <em>Scalar Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.katmatt.graphql.graphQL.impl.ScalarTypeDefinitionImpl
   * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getScalarTypeDefinition()
   * @generated
   */
  int SCALAR_TYPE_DEFINITION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALAR_TYPE_DEFINITION__NAME = TYPE_DEFINITION__NAME;

  /**
   * The number of structural features of the '<em>Scalar Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALAR_TYPE_DEFINITION_FEATURE_COUNT = TYPE_DEFINITION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link io.github.katmatt.graphql.graphQL.impl.ObjectTypeDefinitionImpl <em>Object Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.katmatt.graphql.graphQL.impl.ObjectTypeDefinitionImpl
   * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getObjectTypeDefinition()
   * @generated
   */
  int OBJECT_TYPE_DEFINITION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_TYPE_DEFINITION__NAME = TYPE_DEFINITION__NAME;

  /**
   * The feature id for the '<em><b>Field Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_TYPE_DEFINITION__FIELD_DEFINITIONS = TYPE_DEFINITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Object Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_TYPE_DEFINITION_FEATURE_COUNT = TYPE_DEFINITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link io.github.katmatt.graphql.graphQL.impl.InterfaceDefinitionImpl <em>Interface Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.katmatt.graphql.graphQL.impl.InterfaceDefinitionImpl
   * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getInterfaceDefinition()
   * @generated
   */
  int INTERFACE_DEFINITION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE_DEFINITION__NAME = TYPE_DEFINITION__NAME;

  /**
   * The feature id for the '<em><b>Field Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE_DEFINITION__FIELD_DEFINITIONS = TYPE_DEFINITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Interface Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE_DEFINITION_FEATURE_COUNT = TYPE_DEFINITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link io.github.katmatt.graphql.graphQL.impl.FieldDefinitionImpl <em>Field Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.katmatt.graphql.graphQL.impl.FieldDefinitionImpl
   * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getFieldDefinition()
   * @generated
   */
  int FIELD_DEFINITION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_DEFINITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_DEFINITION__TYPE = 1;

  /**
   * The number of structural features of the '<em>Field Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_DEFINITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.github.katmatt.graphql.graphQL.impl.UnionTypeDefinitionImpl <em>Union Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.katmatt.graphql.graphQL.impl.UnionTypeDefinitionImpl
   * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getUnionTypeDefinition()
   * @generated
   */
  int UNION_TYPE_DEFINITION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNION_TYPE_DEFINITION__NAME = TYPE_DEFINITION__NAME;

  /**
   * The feature id for the '<em><b>Member Types</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNION_TYPE_DEFINITION__MEMBER_TYPES = TYPE_DEFINITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Union Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNION_TYPE_DEFINITION_FEATURE_COUNT = TYPE_DEFINITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link io.github.katmatt.graphql.graphQL.impl.EnumTypeDefinitionImpl <em>Enum Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.katmatt.graphql.graphQL.impl.EnumTypeDefinitionImpl
   * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getEnumTypeDefinition()
   * @generated
   */
  int ENUM_TYPE_DEFINITION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE_DEFINITION__NAME = TYPE_DEFINITION__NAME;

  /**
   * The feature id for the '<em><b>Value Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE_DEFINITION__VALUE_DEFINITIONS = TYPE_DEFINITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Enum Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE_DEFINITION_FEATURE_COUNT = TYPE_DEFINITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link io.github.katmatt.graphql.graphQL.impl.EnumValueDefinitionImpl <em>Enum Value Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.katmatt.graphql.graphQL.impl.EnumValueDefinitionImpl
   * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getEnumValueDefinition()
   * @generated
   */
  int ENUM_VALUE_DEFINITION = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_VALUE_DEFINITION__NAME = 0;

  /**
   * The number of structural features of the '<em>Enum Value Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_VALUE_DEFINITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.github.katmatt.graphql.graphQL.impl.InputObjectTypeDefinitionImpl <em>Input Object Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.katmatt.graphql.graphQL.impl.InputObjectTypeDefinitionImpl
   * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getInputObjectTypeDefinition()
   * @generated
   */
  int INPUT_OBJECT_TYPE_DEFINITION = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_OBJECT_TYPE_DEFINITION__NAME = TYPE_DEFINITION__NAME;

  /**
   * The feature id for the '<em><b>Field Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_OBJECT_TYPE_DEFINITION__FIELD_DEFINITIONS = TYPE_DEFINITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Input Object Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_OBJECT_TYPE_DEFINITION_FEATURE_COUNT = TYPE_DEFINITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link io.github.katmatt.graphql.graphQL.OperationType <em>Operation Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.katmatt.graphql.graphQL.OperationType
   * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getOperationType()
   * @generated
   */
  int OPERATION_TYPE = 12;


  /**
   * Returns the meta object for class '{@link io.github.katmatt.graphql.graphQL.TypeSystemDefinition <em>Type System Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type System Definition</em>'.
   * @see io.github.katmatt.graphql.graphQL.TypeSystemDefinition
   * @generated
   */
  EClass getTypeSystemDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.katmatt.graphql.graphQL.TypeSystemDefinition#getSchemaDefinitions <em>Schema Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Schema Definitions</em>'.
   * @see io.github.katmatt.graphql.graphQL.TypeSystemDefinition#getSchemaDefinitions()
   * @see #getTypeSystemDefinition()
   * @generated
   */
  EReference getTypeSystemDefinition_SchemaDefinitions();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.katmatt.graphql.graphQL.TypeSystemDefinition#getTypeDefinitions <em>Type Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Type Definitions</em>'.
   * @see io.github.katmatt.graphql.graphQL.TypeSystemDefinition#getTypeDefinitions()
   * @see #getTypeSystemDefinition()
   * @generated
   */
  EReference getTypeSystemDefinition_TypeDefinitions();

  /**
   * Returns the meta object for class '{@link io.github.katmatt.graphql.graphQL.SchemaDefinition <em>Schema Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Schema Definition</em>'.
   * @see io.github.katmatt.graphql.graphQL.SchemaDefinition
   * @generated
   */
  EClass getSchemaDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.katmatt.graphql.graphQL.SchemaDefinition#getTypeDefinitions <em>Type Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Type Definitions</em>'.
   * @see io.github.katmatt.graphql.graphQL.SchemaDefinition#getTypeDefinitions()
   * @see #getSchemaDefinition()
   * @generated
   */
  EReference getSchemaDefinition_TypeDefinitions();

  /**
   * Returns the meta object for class '{@link io.github.katmatt.graphql.graphQL.RootOperationTypeDefinition <em>Root Operation Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Root Operation Type Definition</em>'.
   * @see io.github.katmatt.graphql.graphQL.RootOperationTypeDefinition
   * @generated
   */
  EClass getRootOperationTypeDefinition();

  /**
   * Returns the meta object for the attribute '{@link io.github.katmatt.graphql.graphQL.RootOperationTypeDefinition#getOperationType <em>Operation Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation Type</em>'.
   * @see io.github.katmatt.graphql.graphQL.RootOperationTypeDefinition#getOperationType()
   * @see #getRootOperationTypeDefinition()
   * @generated
   */
  EAttribute getRootOperationTypeDefinition_OperationType();

  /**
   * Returns the meta object for the reference '{@link io.github.katmatt.graphql.graphQL.RootOperationTypeDefinition#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see io.github.katmatt.graphql.graphQL.RootOperationTypeDefinition#getType()
   * @see #getRootOperationTypeDefinition()
   * @generated
   */
  EReference getRootOperationTypeDefinition_Type();

  /**
   * Returns the meta object for class '{@link io.github.katmatt.graphql.graphQL.TypeDefinition <em>Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Definition</em>'.
   * @see io.github.katmatt.graphql.graphQL.TypeDefinition
   * @generated
   */
  EClass getTypeDefinition();

  /**
   * Returns the meta object for the attribute '{@link io.github.katmatt.graphql.graphQL.TypeDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.github.katmatt.graphql.graphQL.TypeDefinition#getName()
   * @see #getTypeDefinition()
   * @generated
   */
  EAttribute getTypeDefinition_Name();

  /**
   * Returns the meta object for class '{@link io.github.katmatt.graphql.graphQL.ScalarTypeDefinition <em>Scalar Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scalar Type Definition</em>'.
   * @see io.github.katmatt.graphql.graphQL.ScalarTypeDefinition
   * @generated
   */
  EClass getScalarTypeDefinition();

  /**
   * Returns the meta object for class '{@link io.github.katmatt.graphql.graphQL.ObjectTypeDefinition <em>Object Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Type Definition</em>'.
   * @see io.github.katmatt.graphql.graphQL.ObjectTypeDefinition
   * @generated
   */
  EClass getObjectTypeDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.katmatt.graphql.graphQL.ObjectTypeDefinition#getFieldDefinitions <em>Field Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Field Definitions</em>'.
   * @see io.github.katmatt.graphql.graphQL.ObjectTypeDefinition#getFieldDefinitions()
   * @see #getObjectTypeDefinition()
   * @generated
   */
  EReference getObjectTypeDefinition_FieldDefinitions();

  /**
   * Returns the meta object for class '{@link io.github.katmatt.graphql.graphQL.InterfaceDefinition <em>Interface Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interface Definition</em>'.
   * @see io.github.katmatt.graphql.graphQL.InterfaceDefinition
   * @generated
   */
  EClass getInterfaceDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.katmatt.graphql.graphQL.InterfaceDefinition#getFieldDefinitions <em>Field Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Field Definitions</em>'.
   * @see io.github.katmatt.graphql.graphQL.InterfaceDefinition#getFieldDefinitions()
   * @see #getInterfaceDefinition()
   * @generated
   */
  EReference getInterfaceDefinition_FieldDefinitions();

  /**
   * Returns the meta object for class '{@link io.github.katmatt.graphql.graphQL.FieldDefinition <em>Field Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field Definition</em>'.
   * @see io.github.katmatt.graphql.graphQL.FieldDefinition
   * @generated
   */
  EClass getFieldDefinition();

  /**
   * Returns the meta object for the attribute '{@link io.github.katmatt.graphql.graphQL.FieldDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.github.katmatt.graphql.graphQL.FieldDefinition#getName()
   * @see #getFieldDefinition()
   * @generated
   */
  EAttribute getFieldDefinition_Name();

  /**
   * Returns the meta object for the reference '{@link io.github.katmatt.graphql.graphQL.FieldDefinition#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see io.github.katmatt.graphql.graphQL.FieldDefinition#getType()
   * @see #getFieldDefinition()
   * @generated
   */
  EReference getFieldDefinition_Type();

  /**
   * Returns the meta object for class '{@link io.github.katmatt.graphql.graphQL.UnionTypeDefinition <em>Union Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Union Type Definition</em>'.
   * @see io.github.katmatt.graphql.graphQL.UnionTypeDefinition
   * @generated
   */
  EClass getUnionTypeDefinition();

  /**
   * Returns the meta object for the reference list '{@link io.github.katmatt.graphql.graphQL.UnionTypeDefinition#getMemberTypes <em>Member Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Member Types</em>'.
   * @see io.github.katmatt.graphql.graphQL.UnionTypeDefinition#getMemberTypes()
   * @see #getUnionTypeDefinition()
   * @generated
   */
  EReference getUnionTypeDefinition_MemberTypes();

  /**
   * Returns the meta object for class '{@link io.github.katmatt.graphql.graphQL.EnumTypeDefinition <em>Enum Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Type Definition</em>'.
   * @see io.github.katmatt.graphql.graphQL.EnumTypeDefinition
   * @generated
   */
  EClass getEnumTypeDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.katmatt.graphql.graphQL.EnumTypeDefinition#getValueDefinitions <em>Value Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Value Definitions</em>'.
   * @see io.github.katmatt.graphql.graphQL.EnumTypeDefinition#getValueDefinitions()
   * @see #getEnumTypeDefinition()
   * @generated
   */
  EReference getEnumTypeDefinition_ValueDefinitions();

  /**
   * Returns the meta object for class '{@link io.github.katmatt.graphql.graphQL.EnumValueDefinition <em>Enum Value Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Value Definition</em>'.
   * @see io.github.katmatt.graphql.graphQL.EnumValueDefinition
   * @generated
   */
  EClass getEnumValueDefinition();

  /**
   * Returns the meta object for the attribute '{@link io.github.katmatt.graphql.graphQL.EnumValueDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.github.katmatt.graphql.graphQL.EnumValueDefinition#getName()
   * @see #getEnumValueDefinition()
   * @generated
   */
  EAttribute getEnumValueDefinition_Name();

  /**
   * Returns the meta object for class '{@link io.github.katmatt.graphql.graphQL.InputObjectTypeDefinition <em>Input Object Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input Object Type Definition</em>'.
   * @see io.github.katmatt.graphql.graphQL.InputObjectTypeDefinition
   * @generated
   */
  EClass getInputObjectTypeDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.katmatt.graphql.graphQL.InputObjectTypeDefinition#getFieldDefinitions <em>Field Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Field Definitions</em>'.
   * @see io.github.katmatt.graphql.graphQL.InputObjectTypeDefinition#getFieldDefinitions()
   * @see #getInputObjectTypeDefinition()
   * @generated
   */
  EReference getInputObjectTypeDefinition_FieldDefinitions();

  /**
   * Returns the meta object for enum '{@link io.github.katmatt.graphql.graphQL.OperationType <em>Operation Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operation Type</em>'.
   * @see io.github.katmatt.graphql.graphQL.OperationType
   * @generated
   */
  EEnum getOperationType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GraphQLFactory getGraphQLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link io.github.katmatt.graphql.graphQL.impl.TypeSystemDefinitionImpl <em>Type System Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.katmatt.graphql.graphQL.impl.TypeSystemDefinitionImpl
     * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getTypeSystemDefinition()
     * @generated
     */
    EClass TYPE_SYSTEM_DEFINITION = eINSTANCE.getTypeSystemDefinition();

    /**
     * The meta object literal for the '<em><b>Schema Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE_SYSTEM_DEFINITION__SCHEMA_DEFINITIONS = eINSTANCE.getTypeSystemDefinition_SchemaDefinitions();

    /**
     * The meta object literal for the '<em><b>Type Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE_SYSTEM_DEFINITION__TYPE_DEFINITIONS = eINSTANCE.getTypeSystemDefinition_TypeDefinitions();

    /**
     * The meta object literal for the '{@link io.github.katmatt.graphql.graphQL.impl.SchemaDefinitionImpl <em>Schema Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.katmatt.graphql.graphQL.impl.SchemaDefinitionImpl
     * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getSchemaDefinition()
     * @generated
     */
    EClass SCHEMA_DEFINITION = eINSTANCE.getSchemaDefinition();

    /**
     * The meta object literal for the '<em><b>Type Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEMA_DEFINITION__TYPE_DEFINITIONS = eINSTANCE.getSchemaDefinition_TypeDefinitions();

    /**
     * The meta object literal for the '{@link io.github.katmatt.graphql.graphQL.impl.RootOperationTypeDefinitionImpl <em>Root Operation Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.katmatt.graphql.graphQL.impl.RootOperationTypeDefinitionImpl
     * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getRootOperationTypeDefinition()
     * @generated
     */
    EClass ROOT_OPERATION_TYPE_DEFINITION = eINSTANCE.getRootOperationTypeDefinition();

    /**
     * The meta object literal for the '<em><b>Operation Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOT_OPERATION_TYPE_DEFINITION__OPERATION_TYPE = eINSTANCE.getRootOperationTypeDefinition_OperationType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT_OPERATION_TYPE_DEFINITION__TYPE = eINSTANCE.getRootOperationTypeDefinition_Type();

    /**
     * The meta object literal for the '{@link io.github.katmatt.graphql.graphQL.impl.TypeDefinitionImpl <em>Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.katmatt.graphql.graphQL.impl.TypeDefinitionImpl
     * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getTypeDefinition()
     * @generated
     */
    EClass TYPE_DEFINITION = eINSTANCE.getTypeDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_DEFINITION__NAME = eINSTANCE.getTypeDefinition_Name();

    /**
     * The meta object literal for the '{@link io.github.katmatt.graphql.graphQL.impl.ScalarTypeDefinitionImpl <em>Scalar Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.katmatt.graphql.graphQL.impl.ScalarTypeDefinitionImpl
     * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getScalarTypeDefinition()
     * @generated
     */
    EClass SCALAR_TYPE_DEFINITION = eINSTANCE.getScalarTypeDefinition();

    /**
     * The meta object literal for the '{@link io.github.katmatt.graphql.graphQL.impl.ObjectTypeDefinitionImpl <em>Object Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.katmatt.graphql.graphQL.impl.ObjectTypeDefinitionImpl
     * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getObjectTypeDefinition()
     * @generated
     */
    EClass OBJECT_TYPE_DEFINITION = eINSTANCE.getObjectTypeDefinition();

    /**
     * The meta object literal for the '<em><b>Field Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_TYPE_DEFINITION__FIELD_DEFINITIONS = eINSTANCE.getObjectTypeDefinition_FieldDefinitions();

    /**
     * The meta object literal for the '{@link io.github.katmatt.graphql.graphQL.impl.InterfaceDefinitionImpl <em>Interface Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.katmatt.graphql.graphQL.impl.InterfaceDefinitionImpl
     * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getInterfaceDefinition()
     * @generated
     */
    EClass INTERFACE_DEFINITION = eINSTANCE.getInterfaceDefinition();

    /**
     * The meta object literal for the '<em><b>Field Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERFACE_DEFINITION__FIELD_DEFINITIONS = eINSTANCE.getInterfaceDefinition_FieldDefinitions();

    /**
     * The meta object literal for the '{@link io.github.katmatt.graphql.graphQL.impl.FieldDefinitionImpl <em>Field Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.katmatt.graphql.graphQL.impl.FieldDefinitionImpl
     * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getFieldDefinition()
     * @generated
     */
    EClass FIELD_DEFINITION = eINSTANCE.getFieldDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD_DEFINITION__NAME = eINSTANCE.getFieldDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD_DEFINITION__TYPE = eINSTANCE.getFieldDefinition_Type();

    /**
     * The meta object literal for the '{@link io.github.katmatt.graphql.graphQL.impl.UnionTypeDefinitionImpl <em>Union Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.katmatt.graphql.graphQL.impl.UnionTypeDefinitionImpl
     * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getUnionTypeDefinition()
     * @generated
     */
    EClass UNION_TYPE_DEFINITION = eINSTANCE.getUnionTypeDefinition();

    /**
     * The meta object literal for the '<em><b>Member Types</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNION_TYPE_DEFINITION__MEMBER_TYPES = eINSTANCE.getUnionTypeDefinition_MemberTypes();

    /**
     * The meta object literal for the '{@link io.github.katmatt.graphql.graphQL.impl.EnumTypeDefinitionImpl <em>Enum Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.katmatt.graphql.graphQL.impl.EnumTypeDefinitionImpl
     * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getEnumTypeDefinition()
     * @generated
     */
    EClass ENUM_TYPE_DEFINITION = eINSTANCE.getEnumTypeDefinition();

    /**
     * The meta object literal for the '<em><b>Value Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM_TYPE_DEFINITION__VALUE_DEFINITIONS = eINSTANCE.getEnumTypeDefinition_ValueDefinitions();

    /**
     * The meta object literal for the '{@link io.github.katmatt.graphql.graphQL.impl.EnumValueDefinitionImpl <em>Enum Value Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.katmatt.graphql.graphQL.impl.EnumValueDefinitionImpl
     * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getEnumValueDefinition()
     * @generated
     */
    EClass ENUM_VALUE_DEFINITION = eINSTANCE.getEnumValueDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_VALUE_DEFINITION__NAME = eINSTANCE.getEnumValueDefinition_Name();

    /**
     * The meta object literal for the '{@link io.github.katmatt.graphql.graphQL.impl.InputObjectTypeDefinitionImpl <em>Input Object Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.katmatt.graphql.graphQL.impl.InputObjectTypeDefinitionImpl
     * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getInputObjectTypeDefinition()
     * @generated
     */
    EClass INPUT_OBJECT_TYPE_DEFINITION = eINSTANCE.getInputObjectTypeDefinition();

    /**
     * The meta object literal for the '<em><b>Field Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INPUT_OBJECT_TYPE_DEFINITION__FIELD_DEFINITIONS = eINSTANCE.getInputObjectTypeDefinition_FieldDefinitions();

    /**
     * The meta object literal for the '{@link io.github.katmatt.graphql.graphQL.OperationType <em>Operation Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.katmatt.graphql.graphQL.OperationType
     * @see io.github.katmatt.graphql.graphQL.impl.GraphQLPackageImpl#getOperationType()
     * @generated
     */
    EEnum OPERATION_TYPE = eINSTANCE.getOperationType();

  }

} //GraphQLPackage
