/**
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.graphQL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Object Type Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.katmatt.graphql.graphQL.InputObjectTypeDefinition#getInputsFieldDefinitions <em>Inputs Field Definitions</em>}</li>
 * </ul>
 *
 * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getInputObjectTypeDefinition()
 * @model
 * @generated
 */
public interface InputObjectTypeDefinition extends TypeDefinition
{
  /**
   * Returns the value of the '<em><b>Inputs Field Definitions</b></em>' containment reference list.
   * The list contents are of type {@link io.github.katmatt.graphql.graphQL.InputValueDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inputs Field Definitions</em>' containment reference list.
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getInputObjectTypeDefinition_InputsFieldDefinitions()
   * @model containment="true"
   * @generated
   */
  EList<InputValueDefinition> getInputsFieldDefinitions();

} // InputObjectTypeDefinition
