/**
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.graphQL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.katmatt.graphql.graphQL.ObjectField#getFieldDefinition <em>Field Definition</em>}</li>
 *   <li>{@link io.github.katmatt.graphql.graphQL.ObjectField#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getObjectField()
 * @model
 * @generated
 */
public interface ObjectField extends EObject
{
  /**
   * Returns the value of the '<em><b>Field Definition</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Definition</em>' reference.
   * @see #setFieldDefinition(FieldDefinition)
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getObjectField_FieldDefinition()
   * @model
   * @generated
   */
  FieldDefinition getFieldDefinition();

  /**
   * Sets the value of the '{@link io.github.katmatt.graphql.graphQL.ObjectField#getFieldDefinition <em>Field Definition</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field Definition</em>' reference.
   * @see #getFieldDefinition()
   * @generated
   */
  void setFieldDefinition(FieldDefinition value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(ConstValue)
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getObjectField_Value()
   * @model containment="true"
   * @generated
   */
  ConstValue getValue();

  /**
   * Sets the value of the '{@link io.github.katmatt.graphql.graphQL.ObjectField#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(ConstValue value);

} // ObjectField
