/**
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.graphQL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Schema Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.katmatt.graphql.graphQL.SchemaDefinition#getTypeDefinitions <em>Type Definitions</em>}</li>
 * </ul>
 *
 * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getSchemaDefinition()
 * @model
 * @generated
 */
public interface SchemaDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Definitions</b></em>' containment reference list.
   * The list contents are of type {@link io.github.katmatt.graphql.graphQL.RootOperationTypeDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Definitions</em>' containment reference list.
   * @see io.github.katmatt.graphql.graphQL.GraphQLPackage#getSchemaDefinition_TypeDefinitions()
   * @model containment="true"
   * @generated
   */
  EList<RootOperationTypeDefinition> getTypeDefinitions();

} // SchemaDefinition
