/*
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GraphQLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class TypeSystemDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.TypeSystemDefinition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cSchemaDefinitionsAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cSchemaDefinitionsSchemaDefinitionParserRuleCall_0_0 = (RuleCall)cSchemaDefinitionsAssignment_0.eContents().get(0);
		private final Assignment cTypeDefinitionsAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cTypeDefinitionsTypeDefinitionParserRuleCall_1_0 = (RuleCall)cTypeDefinitionsAssignment_1.eContents().get(0);
		
		//TypeSystemDefinition:
		//	(schemaDefinitions+=SchemaDefinition | typeDefinitions+=TypeDefinition)*;
		@Override public ParserRule getRule() { return rule; }
		
		//(schemaDefinitions+=SchemaDefinition | typeDefinitions+=TypeDefinition)*
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//schemaDefinitions+=SchemaDefinition
		public Assignment getSchemaDefinitionsAssignment_0() { return cSchemaDefinitionsAssignment_0; }
		
		//SchemaDefinition
		public RuleCall getSchemaDefinitionsSchemaDefinitionParserRuleCall_0_0() { return cSchemaDefinitionsSchemaDefinitionParserRuleCall_0_0; }
		
		//typeDefinitions+=TypeDefinition
		public Assignment getTypeDefinitionsAssignment_1() { return cTypeDefinitionsAssignment_1; }
		
		//TypeDefinition
		public RuleCall getTypeDefinitionsTypeDefinitionParserRuleCall_1_0() { return cTypeDefinitionsTypeDefinitionParserRuleCall_1_0; }
	}
	public class SchemaDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.SchemaDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionStringValueParserRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cSchemaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeDefinitionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeDefinitionsRootOperationTypeDefinitionParserRuleCall_3_0 = (RuleCall)cTypeDefinitionsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SchemaDefinition:
		//	description=StringValue? "schema" "{" typeDefinitions+=RootOperationTypeDefinition+ "}";
		@Override public ParserRule getRule() { return rule; }
		
		//description=StringValue? "schema" "{" typeDefinitions+=RootOperationTypeDefinition+ "}"
		public Group getGroup() { return cGroup; }
		
		//description=StringValue?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }
		
		//StringValue
		public RuleCall getDescriptionStringValueParserRuleCall_0_0() { return cDescriptionStringValueParserRuleCall_0_0; }
		
		//"schema"
		public Keyword getSchemaKeyword_1() { return cSchemaKeyword_1; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//typeDefinitions+=RootOperationTypeDefinition+
		public Assignment getTypeDefinitionsAssignment_3() { return cTypeDefinitionsAssignment_3; }
		
		//RootOperationTypeDefinition
		public RuleCall getTypeDefinitionsRootOperationTypeDefinitionParserRuleCall_3_0() { return cTypeDefinitionsRootOperationTypeDefinitionParserRuleCall_3_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class RootOperationTypeDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.RootOperationTypeDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cOperationTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cOperationTypeOperationTypeEnumRuleCall_0_0 = (RuleCall)cOperationTypeAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTypeTypeDefinitionCrossReference_2_0 = (CrossReference)cTypeAssignment_2.eContents().get(0);
		private final RuleCall cTypeTypeDefinitionNAMETerminalRuleCall_2_0_1 = (RuleCall)cTypeTypeDefinitionCrossReference_2_0.eContents().get(1);
		
		//RootOperationTypeDefinition:
		//	operationType=OperationType ":" type=[TypeDefinition|NAME];
		@Override public ParserRule getRule() { return rule; }
		
		//operationType=OperationType ":" type=[TypeDefinition|NAME]
		public Group getGroup() { return cGroup; }
		
		//operationType=OperationType
		public Assignment getOperationTypeAssignment_0() { return cOperationTypeAssignment_0; }
		
		//OperationType
		public RuleCall getOperationTypeOperationTypeEnumRuleCall_0_0() { return cOperationTypeOperationTypeEnumRuleCall_0_0; }
		
		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//type=[TypeDefinition|NAME]
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//[TypeDefinition|NAME]
		public CrossReference getTypeTypeDefinitionCrossReference_2_0() { return cTypeTypeDefinitionCrossReference_2_0; }
		
		//NAME
		public RuleCall getTypeTypeDefinitionNAMETerminalRuleCall_2_0_1() { return cTypeTypeDefinitionNAMETerminalRuleCall_2_0_1; }
	}
	public class TypeDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.TypeDefinition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cScalarTypeDefinitionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cObjectTypeDefinitionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cInterfaceDefinitionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cUnionTypeDefinitionParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cEnumTypeDefinitionParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cInputObjectTypeDefinitionParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//TypeDefinition:
		//	ScalarTypeDefinition | ObjectTypeDefinition | InterfaceDefinition | UnionTypeDefinition | EnumTypeDefinition |
		//	InputObjectTypeDefinition;
		@Override public ParserRule getRule() { return rule; }
		
		//ScalarTypeDefinition | ObjectTypeDefinition | InterfaceDefinition | UnionTypeDefinition | EnumTypeDefinition |
		//InputObjectTypeDefinition
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ScalarTypeDefinition
		public RuleCall getScalarTypeDefinitionParserRuleCall_0() { return cScalarTypeDefinitionParserRuleCall_0; }
		
		//ObjectTypeDefinition
		public RuleCall getObjectTypeDefinitionParserRuleCall_1() { return cObjectTypeDefinitionParserRuleCall_1; }
		
		//InterfaceDefinition
		public RuleCall getInterfaceDefinitionParserRuleCall_2() { return cInterfaceDefinitionParserRuleCall_2; }
		
		//UnionTypeDefinition
		public RuleCall getUnionTypeDefinitionParserRuleCall_3() { return cUnionTypeDefinitionParserRuleCall_3; }
		
		//EnumTypeDefinition
		public RuleCall getEnumTypeDefinitionParserRuleCall_4() { return cEnumTypeDefinitionParserRuleCall_4; }
		
		//InputObjectTypeDefinition
		public RuleCall getInputObjectTypeDefinitionParserRuleCall_5() { return cInputObjectTypeDefinitionParserRuleCall_5; }
	}
	public class ScalarTypeDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.ScalarTypeDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionStringValueParserRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cScalarKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameNAMETerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//ScalarTypeDefinition:
		//	description=StringValue? "scalar" name=NAME;
		@Override public ParserRule getRule() { return rule; }
		
		//description=StringValue? "scalar" name=NAME
		public Group getGroup() { return cGroup; }
		
		//description=StringValue?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }
		
		//StringValue
		public RuleCall getDescriptionStringValueParserRuleCall_0_0() { return cDescriptionStringValueParserRuleCall_0_0; }
		
		//"scalar"
		public Keyword getScalarKeyword_1() { return cScalarKeyword_1; }
		
		//name=NAME
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_2_0() { return cNameNAMETerminalRuleCall_2_0; }
	}
	public class ObjectTypeDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.ObjectTypeDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionStringValueParserRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameNAMETerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cImplementsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cImplementsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cImplementsIntersectionTypeParserRuleCall_3_1_0 = (RuleCall)cImplementsAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cFieldDefinitionsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cFieldDefinitionsFieldDefinitionParserRuleCall_4_1_0 = (RuleCall)cFieldDefinitionsAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		
		//ObjectTypeDefinition:
		//	description=StringValue? "type" name=NAME ('implements' implements=IntersectionType)? ("{"
		//	fieldDefinitions+=FieldDefinition* "}")?;
		@Override public ParserRule getRule() { return rule; }
		
		//description=StringValue? "type" name=NAME ('implements' implements=IntersectionType)? ("{"
		//fieldDefinitions+=FieldDefinition* "}")?
		public Group getGroup() { return cGroup; }
		
		//description=StringValue?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }
		
		//StringValue
		public RuleCall getDescriptionStringValueParserRuleCall_0_0() { return cDescriptionStringValueParserRuleCall_0_0; }
		
		//"type"
		public Keyword getTypeKeyword_1() { return cTypeKeyword_1; }
		
		//name=NAME
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_2_0() { return cNameNAMETerminalRuleCall_2_0; }
		
		//('implements' implements=IntersectionType)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'implements'
		public Keyword getImplementsKeyword_3_0() { return cImplementsKeyword_3_0; }
		
		//implements=IntersectionType
		public Assignment getImplementsAssignment_3_1() { return cImplementsAssignment_3_1; }
		
		//IntersectionType
		public RuleCall getImplementsIntersectionTypeParserRuleCall_3_1_0() { return cImplementsIntersectionTypeParserRuleCall_3_1_0; }
		
		//("{" fieldDefinitions+=FieldDefinition* "}")?
		public Group getGroup_4() { return cGroup_4; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_0() { return cLeftCurlyBracketKeyword_4_0; }
		
		//fieldDefinitions+=FieldDefinition*
		public Assignment getFieldDefinitionsAssignment_4_1() { return cFieldDefinitionsAssignment_4_1; }
		
		//FieldDefinition
		public RuleCall getFieldDefinitionsFieldDefinitionParserRuleCall_4_1_0() { return cFieldDefinitionsFieldDefinitionParserRuleCall_4_1_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_4_2() { return cRightCurlyBracketKeyword_4_2; }
	}
	public class InterfaceDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.InterfaceDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionStringValueParserRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cInterfaceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameNAMETerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cImplementsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cImplementsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cImplementsIntersectionTypeParserRuleCall_3_1_0 = (RuleCall)cImplementsAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cFieldDefinitionsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cFieldDefinitionsFieldDefinitionParserRuleCall_4_1_0 = (RuleCall)cFieldDefinitionsAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		
		//InterfaceDefinition:
		//	description=StringValue? "interface" name=NAME ('implements' implements=IntersectionType)? ("{"
		//	fieldDefinitions+=FieldDefinition* "}")?;
		@Override public ParserRule getRule() { return rule; }
		
		//description=StringValue? "interface" name=NAME ('implements' implements=IntersectionType)? ("{"
		//fieldDefinitions+=FieldDefinition* "}")?
		public Group getGroup() { return cGroup; }
		
		//description=StringValue?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }
		
		//StringValue
		public RuleCall getDescriptionStringValueParserRuleCall_0_0() { return cDescriptionStringValueParserRuleCall_0_0; }
		
		//"interface"
		public Keyword getInterfaceKeyword_1() { return cInterfaceKeyword_1; }
		
		//name=NAME
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_2_0() { return cNameNAMETerminalRuleCall_2_0; }
		
		//('implements' implements=IntersectionType)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'implements'
		public Keyword getImplementsKeyword_3_0() { return cImplementsKeyword_3_0; }
		
		//implements=IntersectionType
		public Assignment getImplementsAssignment_3_1() { return cImplementsAssignment_3_1; }
		
		//IntersectionType
		public RuleCall getImplementsIntersectionTypeParserRuleCall_3_1_0() { return cImplementsIntersectionTypeParserRuleCall_3_1_0; }
		
		//("{" fieldDefinitions+=FieldDefinition* "}")?
		public Group getGroup_4() { return cGroup_4; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_0() { return cLeftCurlyBracketKeyword_4_0; }
		
		//fieldDefinitions+=FieldDefinition*
		public Assignment getFieldDefinitionsAssignment_4_1() { return cFieldDefinitionsAssignment_4_1; }
		
		//FieldDefinition
		public RuleCall getFieldDefinitionsFieldDefinitionParserRuleCall_4_1_0() { return cFieldDefinitionsFieldDefinitionParserRuleCall_4_1_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_4_2() { return cRightCurlyBracketKeyword_4_2; }
	}
	public class FieldDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.FieldDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionStringValueParserRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameNAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeTypeParserRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		
		//FieldDefinition:
		//	description=StringValue? name=NAME ":" type=Type;
		@Override public ParserRule getRule() { return rule; }
		
		//description=StringValue? name=NAME ":" type=Type
		public Group getGroup() { return cGroup; }
		
		//description=StringValue?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }
		
		//StringValue
		public RuleCall getDescriptionStringValueParserRuleCall_0_0() { return cDescriptionStringValueParserRuleCall_0_0; }
		
		//name=NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_1_0() { return cNameNAMETerminalRuleCall_1_0; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//type=Type
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_3_0() { return cTypeTypeParserRuleCall_3_0; }
	}
	public class UnionTypeDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.UnionTypeDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionStringValueParserRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cUnionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameNAMETerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cMemberTypesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cMemberTypesTypeParserRuleCall_3_1_0 = (RuleCall)cMemberTypesAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cVerticalLineKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cMemberTypesAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cMemberTypesTypeParserRuleCall_3_2_1_0 = (RuleCall)cMemberTypesAssignment_3_2_1.eContents().get(0);
		
		//UnionTypeDefinition:
		//	description=StringValue? "union" name=NAME ("=" memberTypes+=Type ("|" memberTypes+=Type)*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//description=StringValue? "union" name=NAME ("=" memberTypes+=Type ("|" memberTypes+=Type)*)?
		public Group getGroup() { return cGroup; }
		
		//description=StringValue?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }
		
		//StringValue
		public RuleCall getDescriptionStringValueParserRuleCall_0_0() { return cDescriptionStringValueParserRuleCall_0_0; }
		
		//"union"
		public Keyword getUnionKeyword_1() { return cUnionKeyword_1; }
		
		//name=NAME
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_2_0() { return cNameNAMETerminalRuleCall_2_0; }
		
		//("=" memberTypes+=Type ("|" memberTypes+=Type)*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//"="
		public Keyword getEqualsSignKeyword_3_0() { return cEqualsSignKeyword_3_0; }
		
		//memberTypes+=Type
		public Assignment getMemberTypesAssignment_3_1() { return cMemberTypesAssignment_3_1; }
		
		//Type
		public RuleCall getMemberTypesTypeParserRuleCall_3_1_0() { return cMemberTypesTypeParserRuleCall_3_1_0; }
		
		//("|" memberTypes+=Type)*
		public Group getGroup_3_2() { return cGroup_3_2; }
		
		//"|"
		public Keyword getVerticalLineKeyword_3_2_0() { return cVerticalLineKeyword_3_2_0; }
		
		//memberTypes+=Type
		public Assignment getMemberTypesAssignment_3_2_1() { return cMemberTypesAssignment_3_2_1; }
		
		//Type
		public RuleCall getMemberTypesTypeParserRuleCall_3_2_1_0() { return cMemberTypesTypeParserRuleCall_3_2_1_0; }
	}
	public class EnumTypeDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.EnumTypeDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionStringValueParserRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cEnumKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameNAMETerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueDefinitionsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueDefinitionsEnumValueDefinitionParserRuleCall_3_1_0 = (RuleCall)cValueDefinitionsAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		
		//EnumTypeDefinition:
		//	description=StringValue? "enum" name=NAME ("{" valueDefinitions+=EnumValueDefinition "}")?;
		@Override public ParserRule getRule() { return rule; }
		
		//description=StringValue? "enum" name=NAME ("{" valueDefinitions+=EnumValueDefinition "}")?
		public Group getGroup() { return cGroup; }
		
		//description=StringValue?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }
		
		//StringValue
		public RuleCall getDescriptionStringValueParserRuleCall_0_0() { return cDescriptionStringValueParserRuleCall_0_0; }
		
		//"enum"
		public Keyword getEnumKeyword_1() { return cEnumKeyword_1; }
		
		//name=NAME
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_2_0() { return cNameNAMETerminalRuleCall_2_0; }
		
		//("{" valueDefinitions+=EnumValueDefinition "}")?
		public Group getGroup_3() { return cGroup_3; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_0() { return cLeftCurlyBracketKeyword_3_0; }
		
		//valueDefinitions+=EnumValueDefinition
		public Assignment getValueDefinitionsAssignment_3_1() { return cValueDefinitionsAssignment_3_1; }
		
		//EnumValueDefinition
		public RuleCall getValueDefinitionsEnumValueDefinitionParserRuleCall_3_1_0() { return cValueDefinitionsEnumValueDefinitionParserRuleCall_3_1_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_3_2() { return cRightCurlyBracketKeyword_3_2; }
	}
	public class EnumValueDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.EnumValueDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionStringValueParserRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameNAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//EnumValueDefinition:
		//	description=StringValue? name=NAME;
		@Override public ParserRule getRule() { return rule; }
		
		//description=StringValue? name=NAME
		public Group getGroup() { return cGroup; }
		
		//description=StringValue?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }
		
		//StringValue
		public RuleCall getDescriptionStringValueParserRuleCall_0_0() { return cDescriptionStringValueParserRuleCall_0_0; }
		
		//name=NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_1_0() { return cNameNAMETerminalRuleCall_1_0; }
	}
	public class InputObjectTypeDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.InputObjectTypeDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionStringValueParserRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cInputKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameNAMETerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cInputsFieldDefinitionsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cInputsFieldDefinitionsInputValueDefinitionParserRuleCall_3_1_0 = (RuleCall)cInputsFieldDefinitionsAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		
		//InputObjectTypeDefinition:
		//	description=StringValue? "input" name=NAME ("{" inputsFieldDefinitions+=InputValueDefinition* "}")?;
		@Override public ParserRule getRule() { return rule; }
		
		//description=StringValue? "input" name=NAME ("{" inputsFieldDefinitions+=InputValueDefinition* "}")?
		public Group getGroup() { return cGroup; }
		
		//description=StringValue?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }
		
		//StringValue
		public RuleCall getDescriptionStringValueParserRuleCall_0_0() { return cDescriptionStringValueParserRuleCall_0_0; }
		
		//"input"
		public Keyword getInputKeyword_1() { return cInputKeyword_1; }
		
		//name=NAME
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_2_0() { return cNameNAMETerminalRuleCall_2_0; }
		
		//("{" inputsFieldDefinitions+=InputValueDefinition* "}")?
		public Group getGroup_3() { return cGroup_3; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_0() { return cLeftCurlyBracketKeyword_3_0; }
		
		//inputsFieldDefinitions+=InputValueDefinition*
		public Assignment getInputsFieldDefinitionsAssignment_3_1() { return cInputsFieldDefinitionsAssignment_3_1; }
		
		//InputValueDefinition
		public RuleCall getInputsFieldDefinitionsInputValueDefinitionParserRuleCall_3_1_0() { return cInputsFieldDefinitionsInputValueDefinitionParserRuleCall_3_1_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_3_2() { return cRightCurlyBracketKeyword_3_2; }
	}
	public class InputValueDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.InputValueDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionStringValueParserRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameNAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeTypeParserRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEqualsSignKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDefaultValueAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDefaultValueConstValueParserRuleCall_4_1_0 = (RuleCall)cDefaultValueAssignment_4_1.eContents().get(0);
		
		//InputValueDefinition:
		//	description=StringValue? name=NAME ":" type=Type ('=' defaultValue=ConstValue)?;
		@Override public ParserRule getRule() { return rule; }
		
		//description=StringValue? name=NAME ":" type=Type ('=' defaultValue=ConstValue)?
		public Group getGroup() { return cGroup; }
		
		//description=StringValue?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }
		
		//StringValue
		public RuleCall getDescriptionStringValueParserRuleCall_0_0() { return cDescriptionStringValueParserRuleCall_0_0; }
		
		//name=NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_1_0() { return cNameNAMETerminalRuleCall_1_0; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//type=Type
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_3_0() { return cTypeTypeParserRuleCall_3_0; }
		
		//('=' defaultValue=ConstValue)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'='
		public Keyword getEqualsSignKeyword_4_0() { return cEqualsSignKeyword_4_0; }
		
		//defaultValue=ConstValue
		public Assignment getDefaultValueAssignment_4_1() { return cDefaultValueAssignment_4_1; }
		
		//ConstValue
		public RuleCall getDefaultValueConstValueParserRuleCall_4_1_0() { return cDefaultValueConstValueParserRuleCall_4_1_0; }
	}
	public class IntersectionTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.IntersectionType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMemberTypesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMemberTypesTypeParserRuleCall_0_0 = (RuleCall)cMemberTypesAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cAmpersandKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cMemberTypesAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cMemberTypesTypeParserRuleCall_1_1_0 = (RuleCall)cMemberTypesAssignment_1_1.eContents().get(0);
		
		//IntersectionType:
		//	memberTypes+=Type ('&' memberTypes+=Type)*;
		@Override public ParserRule getRule() { return rule; }
		
		//memberTypes+=Type ('&' memberTypes+=Type)*
		public Group getGroup() { return cGroup; }
		
		//memberTypes+=Type
		public Assignment getMemberTypesAssignment_0() { return cMemberTypesAssignment_0; }
		
		//Type
		public RuleCall getMemberTypesTypeParserRuleCall_0_0() { return cMemberTypesTypeParserRuleCall_0_0; }
		
		//('&' memberTypes+=Type)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'&'
		public Keyword getAmpersandKeyword_1_0() { return cAmpersandKeyword_1_0; }
		
		//memberTypes+=Type
		public Assignment getMemberTypesAssignment_1_1() { return cMemberTypesAssignment_1_1; }
		
		//Type
		public RuleCall getMemberTypesTypeParserRuleCall_1_1_0() { return cMemberTypesTypeParserRuleCall_1_1_0; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNamedTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cListTypeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Type:
		//	NamedType | ListType;
		@Override public ParserRule getRule() { return rule; }
		
		//NamedType | ListType
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NamedType
		public RuleCall getNamedTypeParserRuleCall_0() { return cNamedTypeParserRuleCall_0; }
		
		//ListType
		public RuleCall getListTypeParserRuleCall_1() { return cListTypeParserRuleCall_1; }
	}
	public class NamedTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.NamedType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeDefinitionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cTypeDefinitionTypeDefinitionCrossReference_0_0 = (CrossReference)cTypeDefinitionAssignment_0.eContents().get(0);
		private final RuleCall cTypeDefinitionTypeDefinitionNAMETerminalRuleCall_0_0_1 = (RuleCall)cTypeDefinitionTypeDefinitionCrossReference_0_0.eContents().get(1);
		private final Assignment cNonNullAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cNonNullExclamationMarkKeyword_1_0 = (Keyword)cNonNullAssignment_1.eContents().get(0);
		
		//NamedType:
		//	typeDefinition=[TypeDefinition|NAME] nonNull?='!'?;
		@Override public ParserRule getRule() { return rule; }
		
		//typeDefinition=[TypeDefinition|NAME] nonNull?='!'?
		public Group getGroup() { return cGroup; }
		
		//typeDefinition=[TypeDefinition|NAME]
		public Assignment getTypeDefinitionAssignment_0() { return cTypeDefinitionAssignment_0; }
		
		//[TypeDefinition|NAME]
		public CrossReference getTypeDefinitionTypeDefinitionCrossReference_0_0() { return cTypeDefinitionTypeDefinitionCrossReference_0_0; }
		
		//NAME
		public RuleCall getTypeDefinitionTypeDefinitionNAMETerminalRuleCall_0_0_1() { return cTypeDefinitionTypeDefinitionNAMETerminalRuleCall_0_0_1; }
		
		//nonNull?='!'?
		public Assignment getNonNullAssignment_1() { return cNonNullAssignment_1; }
		
		//'!'
		public Keyword getNonNullExclamationMarkKeyword_1_0() { return cNonNullExclamationMarkKeyword_1_0; }
	}
	public class ListTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.ListType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeTypeParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNonNullAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cNonNullExclamationMarkKeyword_3_0 = (Keyword)cNonNullAssignment_3.eContents().get(0);
		
		//ListType:
		//	'[' type=Type ']' nonNull?='!'?;
		@Override public ParserRule getRule() { return rule; }
		
		//'[' type=Type ']' nonNull?='!'?
		public Group getGroup() { return cGroup; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }
		
		//type=Type
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_1_0() { return cTypeTypeParserRuleCall_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_2() { return cRightSquareBracketKeyword_2; }
		
		//nonNull?='!'?
		public Assignment getNonNullAssignment_3() { return cNonNullAssignment_3; }
		
		//'!'
		public Keyword getNonNullExclamationMarkKeyword_3_0() { return cNonNullExclamationMarkKeyword_3_0; }
	}
	public class IntValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.IntValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINT_VALUETerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//IntValue:
		//	value=INT_VALUE;
		@Override public ParserRule getRule() { return rule; }
		
		//value=INT_VALUE
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//INT_VALUE
		public RuleCall getValueINT_VALUETerminalRuleCall_0() { return cValueINT_VALUETerminalRuleCall_0; }
	}
	public class FloatValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.FloatValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueFLOAT_VALUETerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//FloatValue:
		//	value=FLOAT_VALUE;
		@Override public ParserRule getRule() { return rule; }
		
		//value=FLOAT_VALUE
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//FLOAT_VALUE
		public RuleCall getValueFLOAT_VALUETerminalRuleCall_0() { return cValueFLOAT_VALUETerminalRuleCall_0; }
	}
	public class NullValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.NullValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cValueNullKeyword_0 = (Keyword)cValueAssignment.eContents().get(0);
		
		//NullValue:
		//	value='null';
		@Override public ParserRule getRule() { return rule; }
		
		//value='null'
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//'null'
		public Keyword getValueNullKeyword_0() { return cValueNullKeyword_0; }
	}
	public class StringValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.StringValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cValueAlternatives_0 = (Alternatives)cValueAssignment.eContents().get(0);
		private final RuleCall cValueSL_STRING_VALUETerminalRuleCall_0_0 = (RuleCall)cValueAlternatives_0.eContents().get(0);
		private final RuleCall cValueML_STRING_VALUETerminalRuleCall_0_1 = (RuleCall)cValueAlternatives_0.eContents().get(1);
		
		//StringValue:
		//	value=(SL_STRING_VALUE | ML_STRING_VALUE);
		@Override public ParserRule getRule() { return rule; }
		
		//value=(SL_STRING_VALUE | ML_STRING_VALUE)
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//(SL_STRING_VALUE | ML_STRING_VALUE)
		public Alternatives getValueAlternatives_0() { return cValueAlternatives_0; }
		
		//SL_STRING_VALUE
		public RuleCall getValueSL_STRING_VALUETerminalRuleCall_0_0() { return cValueSL_STRING_VALUETerminalRuleCall_0_0; }
		
		//ML_STRING_VALUE
		public RuleCall getValueML_STRING_VALUETerminalRuleCall_0_1() { return cValueML_STRING_VALUETerminalRuleCall_0_1; }
	}
	public class BooleanValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.BooleanValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cValueAlternatives_0 = (Alternatives)cValueAssignment.eContents().get(0);
		private final Keyword cValueTrueKeyword_0_0 = (Keyword)cValueAlternatives_0.eContents().get(0);
		private final Keyword cValueFalseKeyword_0_1 = (Keyword)cValueAlternatives_0.eContents().get(1);
		
		//BooleanValue:
		//	value=('true' | 'false');
		@Override public ParserRule getRule() { return rule; }
		
		//value=('true' | 'false')
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//('true' | 'false')
		public Alternatives getValueAlternatives_0() { return cValueAlternatives_0; }
		
		//'true'
		public Keyword getValueTrueKeyword_0_0() { return cValueTrueKeyword_0_0; }
		
		//'false'
		public Keyword getValueFalseKeyword_0_1() { return cValueFalseKeyword_0_1; }
	}
	public class EnumValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.EnumValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cValueEnumValueDefinitionCrossReference_0 = (CrossReference)cValueAssignment.eContents().get(0);
		private final RuleCall cValueEnumValueDefinitionNAMETerminalRuleCall_0_1 = (RuleCall)cValueEnumValueDefinitionCrossReference_0.eContents().get(1);
		
		//EnumValue:
		//	value=[EnumValueDefinition|NAME];
		@Override public ParserRule getRule() { return rule; }
		
		//value=[EnumValueDefinition|NAME]
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//[EnumValueDefinition|NAME]
		public CrossReference getValueEnumValueDefinitionCrossReference_0() { return cValueEnumValueDefinitionCrossReference_0; }
		
		//NAME
		public RuleCall getValueEnumValueDefinitionNAMETerminalRuleCall_0_1() { return cValueEnumValueDefinitionNAMETerminalRuleCall_0_1; }
	}
	public class ObjectValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.ObjectValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cObjectValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFieldsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFieldsObjectFieldParserRuleCall_2_0 = (RuleCall)cFieldsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ObjectValue:
		//	{ObjectValue} '{' fields+=ObjectField* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ObjectValue} '{' fields+=ObjectField* '}'
		public Group getGroup() { return cGroup; }
		
		//{ObjectValue}
		public Action getObjectValueAction_0() { return cObjectValueAction_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//fields+=ObjectField*
		public Assignment getFieldsAssignment_2() { return cFieldsAssignment_2; }
		
		//ObjectField
		public RuleCall getFieldsObjectFieldParserRuleCall_2_0() { return cFieldsObjectFieldParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class ObjectFieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.ObjectField");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cNameFieldDefinitionCrossReference_0_0 = (CrossReference)cNameAssignment_0.eContents().get(0);
		private final RuleCall cNameFieldDefinitionNAMETerminalRuleCall_0_0_1 = (RuleCall)cNameFieldDefinitionCrossReference_0_0.eContents().get(1);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueConstValueParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//ObjectField:
		//	name=[FieldDefinition|NAME] ':' value=ConstValue;
		@Override public ParserRule getRule() { return rule; }
		
		//name=[FieldDefinition|NAME] ':' value=ConstValue
		public Group getGroup() { return cGroup; }
		
		//name=[FieldDefinition|NAME]
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//[FieldDefinition|NAME]
		public CrossReference getNameFieldDefinitionCrossReference_0_0() { return cNameFieldDefinitionCrossReference_0_0; }
		
		//NAME
		public RuleCall getNameFieldDefinitionNAMETerminalRuleCall_0_0_1() { return cNameFieldDefinitionNAMETerminalRuleCall_0_0_1; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//value=ConstValue
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//ConstValue
		public RuleCall getValueConstValueParserRuleCall_2_0() { return cValueConstValueParserRuleCall_2_0; }
	}
	public class ConstValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.ConstValue");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntValueParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFloatValueParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBooleanValueParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cNullValueParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cEnumValueParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cListValueParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cObjectValueParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//ConstValue:
		//	IntValue | FloatValue | BooleanValue | NullValue | EnumValue | ListValue | ObjectValue;
		@Override public ParserRule getRule() { return rule; }
		
		//IntValue | FloatValue | BooleanValue | NullValue | EnumValue | ListValue | ObjectValue
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IntValue
		public RuleCall getIntValueParserRuleCall_0() { return cIntValueParserRuleCall_0; }
		
		//FloatValue
		public RuleCall getFloatValueParserRuleCall_1() { return cFloatValueParserRuleCall_1; }
		
		//BooleanValue
		public RuleCall getBooleanValueParserRuleCall_2() { return cBooleanValueParserRuleCall_2; }
		
		//NullValue
		public RuleCall getNullValueParserRuleCall_3() { return cNullValueParserRuleCall_3; }
		
		//EnumValue
		public RuleCall getEnumValueParserRuleCall_4() { return cEnumValueParserRuleCall_4; }
		
		//ListValue
		public RuleCall getListValueParserRuleCall_5() { return cListValueParserRuleCall_5; }
		
		//ObjectValue
		public RuleCall getObjectValueParserRuleCall_6() { return cObjectValueParserRuleCall_6; }
	}
	public class ListValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.ListValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cListValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValuesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValuesConstValueParserRuleCall_2_0 = (RuleCall)cValuesAssignment_2.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ListValue:
		//	{ListValue} '[' values+=ConstValue* ']';
		@Override public ParserRule getRule() { return rule; }
		
		//{ListValue} '[' values+=ConstValue* ']'
		public Group getGroup() { return cGroup; }
		
		//{ListValue}
		public Action getListValueAction_0() { return cListValueAction_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }
		
		//values+=ConstValue*
		public Assignment getValuesAssignment_2() { return cValuesAssignment_2; }
		
		//ConstValue
		public RuleCall getValuesConstValueParserRuleCall_2_0() { return cValuesConstValueParserRuleCall_2_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}
	
	public class OperationTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.OperationType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cQUERYEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cQUERYQueryKeyword_0_0 = (Keyword)cQUERYEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMUTATIONEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMUTATIONMutationKeyword_1_0 = (Keyword)cMUTATIONEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSUBSCRIPTIONEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSUBSCRIPTIONSubscriptionKeyword_2_0 = (Keyword)cSUBSCRIPTIONEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum OperationType:
		//	QUERY="query" |
		//	MUTATION="mutation" |
		//	SUBSCRIPTION="subscription";
		public EnumRule getRule() { return rule; }
		
		//QUERY="query" | MUTATION="mutation" | SUBSCRIPTION="subscription"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//QUERY="query"
		public EnumLiteralDeclaration getQUERYEnumLiteralDeclaration_0() { return cQUERYEnumLiteralDeclaration_0; }
		
		//"query"
		public Keyword getQUERYQueryKeyword_0_0() { return cQUERYQueryKeyword_0_0; }
		
		//MUTATION="mutation"
		public EnumLiteralDeclaration getMUTATIONEnumLiteralDeclaration_1() { return cMUTATIONEnumLiteralDeclaration_1; }
		
		//"mutation"
		public Keyword getMUTATIONMutationKeyword_1_0() { return cMUTATIONMutationKeyword_1_0; }
		
		//SUBSCRIPTION="subscription"
		public EnumLiteralDeclaration getSUBSCRIPTIONEnumLiteralDeclaration_2() { return cSUBSCRIPTIONEnumLiteralDeclaration_2; }
		
		//"subscription"
		public Keyword getSUBSCRIPTIONSubscriptionKeyword_2_0() { return cSUBSCRIPTIONSubscriptionKeyword_2_0; }
	}
	
	private final TypeSystemDefinitionElements pTypeSystemDefinition;
	private final SchemaDefinitionElements pSchemaDefinition;
	private final RootOperationTypeDefinitionElements pRootOperationTypeDefinition;
	private final TypeDefinitionElements pTypeDefinition;
	private final ScalarTypeDefinitionElements pScalarTypeDefinition;
	private final ObjectTypeDefinitionElements pObjectTypeDefinition;
	private final InterfaceDefinitionElements pInterfaceDefinition;
	private final FieldDefinitionElements pFieldDefinition;
	private final UnionTypeDefinitionElements pUnionTypeDefinition;
	private final EnumTypeDefinitionElements pEnumTypeDefinition;
	private final EnumValueDefinitionElements pEnumValueDefinition;
	private final InputObjectTypeDefinitionElements pInputObjectTypeDefinition;
	private final InputValueDefinitionElements pInputValueDefinition;
	private final IntersectionTypeElements pIntersectionType;
	private final TypeElements pType;
	private final NamedTypeElements pNamedType;
	private final ListTypeElements pListType;
	private final IntValueElements pIntValue;
	private final FloatValueElements pFloatValue;
	private final NullValueElements pNullValue;
	private final StringValueElements pStringValue;
	private final BooleanValueElements pBooleanValue;
	private final EnumValueElements pEnumValue;
	private final ObjectValueElements pObjectValue;
	private final ObjectFieldElements pObjectField;
	private final ConstValueElements pConstValue;
	private final ListValueElements pListValue;
	private final OperationTypeElements eOperationType;
	private final TerminalRule tNAME;
	private final TerminalRule tINT_VALUE;
	private final TerminalRule tFLOAT_VALUE;
	private final TerminalRule tWS;
	private final TerminalRule tSL_COMMENT;
	private final TerminalRule tCOMMA;
	private final TerminalRule tSL_STRING_VALUE;
	private final TerminalRule tML_STRING_VALUE;
	private final TerminalRule tSTRING_CHARACTER;
	
	private final Grammar grammar;

	@Inject
	public GraphQLGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.pTypeSystemDefinition = new TypeSystemDefinitionElements();
		this.pSchemaDefinition = new SchemaDefinitionElements();
		this.pRootOperationTypeDefinition = new RootOperationTypeDefinitionElements();
		this.pTypeDefinition = new TypeDefinitionElements();
		this.pScalarTypeDefinition = new ScalarTypeDefinitionElements();
		this.pObjectTypeDefinition = new ObjectTypeDefinitionElements();
		this.pInterfaceDefinition = new InterfaceDefinitionElements();
		this.pFieldDefinition = new FieldDefinitionElements();
		this.pUnionTypeDefinition = new UnionTypeDefinitionElements();
		this.pEnumTypeDefinition = new EnumTypeDefinitionElements();
		this.pEnumValueDefinition = new EnumValueDefinitionElements();
		this.pInputObjectTypeDefinition = new InputObjectTypeDefinitionElements();
		this.pInputValueDefinition = new InputValueDefinitionElements();
		this.pIntersectionType = new IntersectionTypeElements();
		this.pType = new TypeElements();
		this.pNamedType = new NamedTypeElements();
		this.pListType = new ListTypeElements();
		this.pIntValue = new IntValueElements();
		this.pFloatValue = new FloatValueElements();
		this.pNullValue = new NullValueElements();
		this.pStringValue = new StringValueElements();
		this.pBooleanValue = new BooleanValueElements();
		this.pEnumValue = new EnumValueElements();
		this.pObjectValue = new ObjectValueElements();
		this.pObjectField = new ObjectFieldElements();
		this.pConstValue = new ConstValueElements();
		this.pListValue = new ListValueElements();
		this.eOperationType = new OperationTypeElements();
		this.tNAME = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.NAME");
		this.tINT_VALUE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.INT_VALUE");
		this.tFLOAT_VALUE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.FLOAT_VALUE");
		this.tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.WS");
		this.tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.SL_COMMENT");
		this.tCOMMA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.COMMA");
		this.tSL_STRING_VALUE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.SL_STRING_VALUE");
		this.tML_STRING_VALUE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.ML_STRING_VALUE");
		this.tSTRING_CHARACTER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "io.github.katmatt.graphql.GraphQL.STRING_CHARACTER");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("io.github.katmatt.graphql.GraphQL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//TypeSystemDefinition:
	//	(schemaDefinitions+=SchemaDefinition | typeDefinitions+=TypeDefinition)*;
	public TypeSystemDefinitionElements getTypeSystemDefinitionAccess() {
		return pTypeSystemDefinition;
	}
	
	public ParserRule getTypeSystemDefinitionRule() {
		return getTypeSystemDefinitionAccess().getRule();
	}
	
	//SchemaDefinition:
	//	description=StringValue? "schema" "{" typeDefinitions+=RootOperationTypeDefinition+ "}";
	public SchemaDefinitionElements getSchemaDefinitionAccess() {
		return pSchemaDefinition;
	}
	
	public ParserRule getSchemaDefinitionRule() {
		return getSchemaDefinitionAccess().getRule();
	}
	
	//RootOperationTypeDefinition:
	//	operationType=OperationType ":" type=[TypeDefinition|NAME];
	public RootOperationTypeDefinitionElements getRootOperationTypeDefinitionAccess() {
		return pRootOperationTypeDefinition;
	}
	
	public ParserRule getRootOperationTypeDefinitionRule() {
		return getRootOperationTypeDefinitionAccess().getRule();
	}
	
	//TypeDefinition:
	//	ScalarTypeDefinition | ObjectTypeDefinition | InterfaceDefinition | UnionTypeDefinition | EnumTypeDefinition |
	//	InputObjectTypeDefinition;
	public TypeDefinitionElements getTypeDefinitionAccess() {
		return pTypeDefinition;
	}
	
	public ParserRule getTypeDefinitionRule() {
		return getTypeDefinitionAccess().getRule();
	}
	
	//ScalarTypeDefinition:
	//	description=StringValue? "scalar" name=NAME;
	public ScalarTypeDefinitionElements getScalarTypeDefinitionAccess() {
		return pScalarTypeDefinition;
	}
	
	public ParserRule getScalarTypeDefinitionRule() {
		return getScalarTypeDefinitionAccess().getRule();
	}
	
	//ObjectTypeDefinition:
	//	description=StringValue? "type" name=NAME ('implements' implements=IntersectionType)? ("{"
	//	fieldDefinitions+=FieldDefinition* "}")?;
	public ObjectTypeDefinitionElements getObjectTypeDefinitionAccess() {
		return pObjectTypeDefinition;
	}
	
	public ParserRule getObjectTypeDefinitionRule() {
		return getObjectTypeDefinitionAccess().getRule();
	}
	
	//InterfaceDefinition:
	//	description=StringValue? "interface" name=NAME ('implements' implements=IntersectionType)? ("{"
	//	fieldDefinitions+=FieldDefinition* "}")?;
	public InterfaceDefinitionElements getInterfaceDefinitionAccess() {
		return pInterfaceDefinition;
	}
	
	public ParserRule getInterfaceDefinitionRule() {
		return getInterfaceDefinitionAccess().getRule();
	}
	
	//FieldDefinition:
	//	description=StringValue? name=NAME ":" type=Type;
	public FieldDefinitionElements getFieldDefinitionAccess() {
		return pFieldDefinition;
	}
	
	public ParserRule getFieldDefinitionRule() {
		return getFieldDefinitionAccess().getRule();
	}
	
	//UnionTypeDefinition:
	//	description=StringValue? "union" name=NAME ("=" memberTypes+=Type ("|" memberTypes+=Type)*)?;
	public UnionTypeDefinitionElements getUnionTypeDefinitionAccess() {
		return pUnionTypeDefinition;
	}
	
	public ParserRule getUnionTypeDefinitionRule() {
		return getUnionTypeDefinitionAccess().getRule();
	}
	
	//EnumTypeDefinition:
	//	description=StringValue? "enum" name=NAME ("{" valueDefinitions+=EnumValueDefinition "}")?;
	public EnumTypeDefinitionElements getEnumTypeDefinitionAccess() {
		return pEnumTypeDefinition;
	}
	
	public ParserRule getEnumTypeDefinitionRule() {
		return getEnumTypeDefinitionAccess().getRule();
	}
	
	//EnumValueDefinition:
	//	description=StringValue? name=NAME;
	public EnumValueDefinitionElements getEnumValueDefinitionAccess() {
		return pEnumValueDefinition;
	}
	
	public ParserRule getEnumValueDefinitionRule() {
		return getEnumValueDefinitionAccess().getRule();
	}
	
	//InputObjectTypeDefinition:
	//	description=StringValue? "input" name=NAME ("{" inputsFieldDefinitions+=InputValueDefinition* "}")?;
	public InputObjectTypeDefinitionElements getInputObjectTypeDefinitionAccess() {
		return pInputObjectTypeDefinition;
	}
	
	public ParserRule getInputObjectTypeDefinitionRule() {
		return getInputObjectTypeDefinitionAccess().getRule();
	}
	
	//InputValueDefinition:
	//	description=StringValue? name=NAME ":" type=Type ('=' defaultValue=ConstValue)?;
	public InputValueDefinitionElements getInputValueDefinitionAccess() {
		return pInputValueDefinition;
	}
	
	public ParserRule getInputValueDefinitionRule() {
		return getInputValueDefinitionAccess().getRule();
	}
	
	//IntersectionType:
	//	memberTypes+=Type ('&' memberTypes+=Type)*;
	public IntersectionTypeElements getIntersectionTypeAccess() {
		return pIntersectionType;
	}
	
	public ParserRule getIntersectionTypeRule() {
		return getIntersectionTypeAccess().getRule();
	}
	
	//Type:
	//	NamedType | ListType;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//NamedType:
	//	typeDefinition=[TypeDefinition|NAME] nonNull?='!'?;
	public NamedTypeElements getNamedTypeAccess() {
		return pNamedType;
	}
	
	public ParserRule getNamedTypeRule() {
		return getNamedTypeAccess().getRule();
	}
	
	//ListType:
	//	'[' type=Type ']' nonNull?='!'?;
	public ListTypeElements getListTypeAccess() {
		return pListType;
	}
	
	public ParserRule getListTypeRule() {
		return getListTypeAccess().getRule();
	}
	
	//IntValue:
	//	value=INT_VALUE;
	public IntValueElements getIntValueAccess() {
		return pIntValue;
	}
	
	public ParserRule getIntValueRule() {
		return getIntValueAccess().getRule();
	}
	
	//FloatValue:
	//	value=FLOAT_VALUE;
	public FloatValueElements getFloatValueAccess() {
		return pFloatValue;
	}
	
	public ParserRule getFloatValueRule() {
		return getFloatValueAccess().getRule();
	}
	
	//NullValue:
	//	value='null';
	public NullValueElements getNullValueAccess() {
		return pNullValue;
	}
	
	public ParserRule getNullValueRule() {
		return getNullValueAccess().getRule();
	}
	
	//StringValue:
	//	value=(SL_STRING_VALUE | ML_STRING_VALUE);
	public StringValueElements getStringValueAccess() {
		return pStringValue;
	}
	
	public ParserRule getStringValueRule() {
		return getStringValueAccess().getRule();
	}
	
	//BooleanValue:
	//	value=('true' | 'false');
	public BooleanValueElements getBooleanValueAccess() {
		return pBooleanValue;
	}
	
	public ParserRule getBooleanValueRule() {
		return getBooleanValueAccess().getRule();
	}
	
	//EnumValue:
	//	value=[EnumValueDefinition|NAME];
	public EnumValueElements getEnumValueAccess() {
		return pEnumValue;
	}
	
	public ParserRule getEnumValueRule() {
		return getEnumValueAccess().getRule();
	}
	
	//ObjectValue:
	//	{ObjectValue} '{' fields+=ObjectField* '}';
	public ObjectValueElements getObjectValueAccess() {
		return pObjectValue;
	}
	
	public ParserRule getObjectValueRule() {
		return getObjectValueAccess().getRule();
	}
	
	//ObjectField:
	//	name=[FieldDefinition|NAME] ':' value=ConstValue;
	public ObjectFieldElements getObjectFieldAccess() {
		return pObjectField;
	}
	
	public ParserRule getObjectFieldRule() {
		return getObjectFieldAccess().getRule();
	}
	
	//ConstValue:
	//	IntValue | FloatValue | BooleanValue | NullValue | EnumValue | ListValue | ObjectValue;
	public ConstValueElements getConstValueAccess() {
		return pConstValue;
	}
	
	public ParserRule getConstValueRule() {
		return getConstValueAccess().getRule();
	}
	
	//ListValue:
	//	{ListValue} '[' values+=ConstValue* ']';
	public ListValueElements getListValueAccess() {
		return pListValue;
	}
	
	public ParserRule getListValueRule() {
		return getListValueAccess().getRule();
	}
	
	//enum OperationType:
	//	QUERY="query" |
	//	MUTATION="mutation" |
	//	SUBSCRIPTION="subscription";
	public OperationTypeElements getOperationTypeAccess() {
		return eOperationType;
	}
	
	public EnumRule getOperationTypeRule() {
		return getOperationTypeAccess().getRule();
	}
	
	//terminal NAME:
	//	('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getNAMERule() {
		return tNAME;
	}
	
	//terminal INT_VALUE:
	//	'-'? '1'..'9' '0'..'9'*;
	public TerminalRule getINT_VALUERule() {
		return tINT_VALUE;
	}
	
	//terminal FLOAT_VALUE:
	//	'-'? ('0' | '1'..'9'*) '.' '0'..'9'* (('e' | 'E') ('+' | '-')? '0'..'9'*);
	public TerminalRule getFLOAT_VALUERule() {
		return tFLOAT_VALUE;
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return tWS;
	}
	
	//terminal SL_COMMENT:
	//	'#' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return tSL_COMMENT;
	}
	
	//terminal COMMA:
	//	',';
	public TerminalRule getCOMMARule() {
		return tCOMMA;
	}
	
	//terminal SL_STRING_VALUE:
	//	'"' STRING_CHARACTER* '"';
	public TerminalRule getSL_STRING_VALUERule() {
		return tSL_STRING_VALUE;
	}
	
	//terminal ML_STRING_VALUE:
	//	'"""'->'"""';
	public TerminalRule getML_STRING_VALUERule() {
		return tML_STRING_VALUE;
	}
	
	//terminal STRING_CHARACTER:
	//	!('\n' | '\r' | '"' | '\\');
	public TerminalRule getSTRING_CHARACTERRule() {
		return tSTRING_CHARACTER;
	}
}
