/*
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class GraphQLProposalProvider extends AbstractGraphQLProposalProvider {
}
