/*
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GraphQLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("io/github/katmatt/graphql/parser/antlr/internal/InternalGraphQL.tokens");
	}
}
