/*
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.parser.antlr;

import com.google.inject.Inject;
import io.github.katmatt.graphql.parser.antlr.internal.InternalGraphQLParser;
import io.github.katmatt.graphql.services.GraphQLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GraphQLParser extends AbstractAntlrParser {

	@Inject
	private GraphQLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT", "RULE_COMMA");
	}
	

	@Override
	protected InternalGraphQLParser createParser(XtextTokenStream stream) {
		return new InternalGraphQLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TypeSystemDefinition";
	}

	public GraphQLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GraphQLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
