/*
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GraphQLStandaloneSetup extends GraphQLStandaloneSetupGenerated {

	public static void doSetup() {
		new GraphQLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
