/*
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGraphQLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(io.github.katmatt.graphql.graphQL.GraphQLPackage.eINSTANCE);
		return result;
	}
}
