/**
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.graphQL.impl;

import io.github.katmatt.graphql.graphQL.GraphQLPackage;
import io.github.katmatt.graphql.graphQL.InputObjectTypeDefinition;
import io.github.katmatt.graphql.graphQL.InputValueDefinition;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Input Object Type Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.github.katmatt.graphql.graphQL.impl.InputObjectTypeDefinitionImpl#getInputFieldsDefinition <em>Input Fields Definition</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InputObjectTypeDefinitionImpl extends TypeDefinitionImpl implements InputObjectTypeDefinition
{
  /**
   * The cached value of the '{@link #getInputFieldsDefinition() <em>Input Fields Definition</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputFieldsDefinition()
   * @generated
   * @ordered
   */
  protected EList<InputValueDefinition> inputFieldsDefinition;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InputObjectTypeDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GraphQLPackage.Literals.INPUT_OBJECT_TYPE_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<InputValueDefinition> getInputFieldsDefinition()
  {
    if (inputFieldsDefinition == null)
    {
      inputFieldsDefinition = new EObjectContainmentEList<InputValueDefinition>(InputValueDefinition.class, this, GraphQLPackage.INPUT_OBJECT_TYPE_DEFINITION__INPUT_FIELDS_DEFINITION);
    }
    return inputFieldsDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GraphQLPackage.INPUT_OBJECT_TYPE_DEFINITION__INPUT_FIELDS_DEFINITION:
        return ((InternalEList<?>)getInputFieldsDefinition()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GraphQLPackage.INPUT_OBJECT_TYPE_DEFINITION__INPUT_FIELDS_DEFINITION:
        return getInputFieldsDefinition();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GraphQLPackage.INPUT_OBJECT_TYPE_DEFINITION__INPUT_FIELDS_DEFINITION:
        getInputFieldsDefinition().clear();
        getInputFieldsDefinition().addAll((Collection<? extends InputValueDefinition>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GraphQLPackage.INPUT_OBJECT_TYPE_DEFINITION__INPUT_FIELDS_DEFINITION:
        getInputFieldsDefinition().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GraphQLPackage.INPUT_OBJECT_TYPE_DEFINITION__INPUT_FIELDS_DEFINITION:
        return inputFieldsDefinition != null && !inputFieldsDefinition.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //InputObjectTypeDefinitionImpl
