/*
 * generated by Xtext 2.23.0
 */
package io.github.katmatt.graphql.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import io.github.katmatt.graphql.graphQL.SchemaDefinition

@ExtendWith(InjectionExtension)
@InjectWith(GraphQLInjectorProvider)
class GraphQLParsingTest {
	@Inject
	ParseHelper<SchemaDefinition> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			schema {
				query : Test
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
